version: '3.9'

services:
  java_app:
    container_name: inventario_app
    image: ipt-java-app:1.0.0
    build: .
    ports:
      - 2020:2020
    environment:
      - DATABASE_URL = jdbc:postgresql://127.0.0.1:5432/Inventario
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = Andres1738
    depends_on:
      - java_db
  java_db:
      container_name: java_db
      image: postgres:12
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Andres1738
        POSTGRES_DB: Inventario
